name: Release on Stable

on:
  push:
    branches:
      - stable

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Gradle build
        run: ./gradlew build

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: stable-${{ github.run_number }}
          name: Release stable build #${{ github.run_number }}
          body: |
            Automated release from stable branch.
          draft: false
          prerelease: false

